export enum ToastStatus {
  OPEN_TO_CONTRIBUTION = 'OPEN_TO_CONTRIBUTION',
  OPEN_FOR_VOTE = 'OPEN_FOR_VOTE',
  VOTE_CLOSED = 'VOTE_CLOSED',
  WAITING_FOR_TOAST = 'WAITING_FOR_TOAST',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}
