test:functions:
  stage: test
  tags: [ docker, ekino, france ]
  only:
    changes:
      - firebase/**/*
  artifacts:
    paths:
      - firebase/functions/lib
  script:
    - yarn workspace functions build

deploy:functions:
  stage: deploy
  tags: [ docker, ekino, france ]
  only:
    refs:
      - master
    changes:
      - firebase/**/*
  needs:
    - job: test:functions
      artifacts: true
  script:
    - cd firebase
    - firebase deploy --only functions
