enum NotificationType {
  ADD_SUBJECT = 'ADD_SUBJECT',
  EDIT_SUBJECT_CONTENT = 'EDIT_SUBJECT_CONTENT',
  REMOVE_SUBJECT = 'REMOVE_SUBJECT',
  EDIT_SUBJECT_STATUS = 'EDIT_SUBJECT_STATUS',
  CREATE_TOAST = 'CREATE_TOAST',
  EDIT_TOAST_INFOS = 'EDIT_TOAST_INFOS',
  EDIT_TOAST_STATUS = 'EDIT_TOAST_STATUS',
}

export default NotificationType;
