test-web:
  stage: test
  tags: [ docker, ekino, france ]
  only:
    changes:
      - web/**/*
  artifacts:
    paths:
      - firebase/dist
  variables:
    VITE_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
    VITE_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
    VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
    VITE_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    VITE_FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
  script:
    - cd web
    - NODE_ENV=production pnpm build

deploy-web:
  stage: deploy
  tags: [ docker, ekino, france ]
  only:
    refs:
      - master
    changes:
      - web/**/*
  needs:
    - job: test-web
      artifacts: true
  script:
    - cd firebase
    - firebase deploy --only hosting
